### ISSUE TITLE
Research on more Data sources and extract data from them

### ISSUE THREAD

**Issue by jonas-he** [PokemonGoers/PokeData#1]

**Comment by jonas-he** [comment]
https://www.reddit.com/r/pokemongodev/comments/4trjum/pok%C3%A9mon_go_development_archive_works_in_progress/

**Comment by jonas-he** [comment]
https://www.reddit.com/r/thesilphroad

**Comment by sacdallago** [comment]
This kind of issue is OK. Remember to use **labels** to filter the different issues in types, eg:
- feature
- bug
- question
- research
- discussion
- ...

**Comment by gyachdav** [comment]
Rare pokemons trakcer
http://pokesnipers.com/

**Comment by sacdallago** [comment]
https://reddit.com/r/pokemongodev

**Comment by jonas-he** [comment]
Thanks for the hints! 
So far I identified some other sources apart from pokeradar.io:
- host: pokecrew.com
  - api path: https://api.pokecrew.com/api/v1/seens
  - parameters: center_latitude, center_longitude, northeast_latitude, northeast_longitude, southwest_latitude, southwest_longitude, pokemon_id (leave blank for all pokemon), live, minimal (don't yet know what live and minimal are for)
- host: skiplagged.com
  - api path: https://skiplagged.com/api/pokemon.php
  - parameters: e.g. bounds=40.627972,-74.268557,40.876348,-73.852793 (min_latitude, min_longitude, max_latitude, max_longtitude)
- host pokesnipers.com
  - api path: http://pokesnipers.com/api/v1/pokemon.json
  - parameters: none

**Comment by jonas-he** [comment]
- host: pokemapper.co
  - api path: https://pokemapper.global.ssl.fastly.net/sightings
  - parameters: limit
- host: pokelive.io (you can see map, but api requests don't get answered - timeout)
  - api path: http://pokelive.io/api/data
  - parameters: lat1, lat2, lng1, lng2
- host: pokemaplive.com (note: one request takes about 15-30 seconds)
  - api path: https://api.pokemaplive.com/api_v4.php
  - parameters: action=get, minLat, minLng, maxLat, maxLng

**Comment by sacdallago** [comment]
for me pokemapper.co works :)

**Comment by jonas-he** [comment]
Tried Firefox now instead of Chrome and it works, thx! Edited previous comment.

**Comment by samitsv** [comment]
https://pokeapi.co/

**Comment by jonas-he** [comment]
some interesting statistical data from pokeradar: https://docs.google.com/document/d/1iZeW3wt-h-L7v97FaDLSjqxFysTLQef92c1nNOqt3Tk/edit

**Comment by fabe85** [comment]
This is indeed very interesting and I could imagine that this could also be very informative for ML. I would add this spawn feature represented as a percentage in a separate branch where I add all the other feature still missing.

**Comment by jonas-he** [comment]
- host: fastpokemap.se (api calls not working when calling URL manually, maybe has something to do with request headers)
  - api: https://cache.fastpokemap.se and https://api.fastpokemap.se
  - parameter: lat,lng

**Comment by jonas-he** [comment]
i think this are enough sources, listener script for pokeradar can easily be adapted to them. However I won't close it because i want to look up the sources in the future :)

**Comment by gyachdav** [comment]
How many sources are being scraped then?

**Comment by samitsv** [comment]
@gyachdav at the moment we have three of them: PokeRadar, PokeSniper and Twitter

**Comment by jonas-he** [comment]
@gyachdav Currently we have implemented: pokeRadar, pokesniper, twitter, pokecrew, skiplagged, fastpokemap (work in progress) however they are not being scraped atm because @sacdallago has to setup the servers and everything...

**Comment by sacdallago** [comment]
@gyachdav didn't want to do this before we had the node in rostlab because migrating is just another headache and setting it up twice is no fun either..

**Comment by jonas-he** [comment]
https://www.pokemap.net/
Their API is somehow obfuscated/encrypted. So would have to be reverse engineered to get the pokemons. Or use something like a browser emulator like phantomJS or selenium.
Dont know if its worth the effort.

**Comment by jonas-he** [comment]
https://pokelocate.io/
only for toronto

**Comment by jonas-he** [comment]
Pokemon sniping sites:
http://pokesniper.org/
http://pokezz.com/
https://pokedexs.com/
Pokemon Live map:
https://pokeraider.com/

**Comment by jonas-he** [comment]
Also has statistics about spawn points
https://pokemonradar.de/

**Comment by sacdallago** [comment]
@PokemonGoers/pokedata hey guys, was wondering if the Gym data integration that @juanmirocks talked about in some issue was being considered by someone :)
