### ISSUE TITLE
Evolution data 

### ISSUE THREAD

**Issue by gyachdav** [PokemonGoers/PokeData#108]
tried 
http://pokedata.c4e3f8c7.svc.dockerapp.io:65014/api/pokemon/evolution/prev/name/Voltorb

Resp:
{
 "message": "Success",
    "data": [
        {
            "_id": "57c7433d7db332a41b06d7c5",
            "maxHP": 1646,
            "maxCP": 1496,
            "fleeRate": 0.06,
            "classification": "Ball Pokèmon",
            "name": "Electrode",
...}
]
}

whereas [cannon](http://bulbapedia.bulbagarden.net/wiki/Voltorb_%28Pok%C3%A9mon%29) says:

Voltorb -> Electrode

trying 

http://pokedata.c4e3f8c7.svc.dockerapp.io:65014/api/pokemon/evolution/next/name/Voltorb

gets me an empty resp. 

Now I understand what you're trying to do here but it is counter intuitive. I would recommend to either:
1.  change the logic of this operation to find the EvolveTo

or 
1. change the name of the operation to EvolveFrom

or
1. Have two operations: EvolveTo and EvolveFrom. 

and have a better description, right now it is confusing.

**Comment by jonas-he** [comment]
@gyachdav indeed, theres a mistake in our logic, im looking into this.

**Comment by swathi-ssunder** [comment]
@jonas-he - The problem is not with the logic, but rather with the naming, as @gyachdav rightly pointed out. And this has led to the confusion in interpreting the API response.
So we can change it as per the suggestions.

**Comment by jonas-he** [comment]
@gyachdav its fixed now. also these API calls will only return the direct next/previous evolution, not all of them.

**Comment by gyachdav** [comment]
LGTM
