### ISSUE TITLE
Json field name missmatch

### ISSUE THREAD

**Issue by Aurel-Roci** [PokemonGoers/PokeData#110]
Hi guys, I noticed that the pokemonId field has two different names:
pokemonId 
pokemonID
Can you fix this?

Thanks

**Comment by swathi-ssunder** [comment]
@Aurel-Roci - Hey, I had noticed this issue on 31st and fixed it. So if you tested this on 31st, then yes, this discrepancy existed.
See https://github.com/PokemonGoers/PokeData/commit/e59655475c1538e6261b558b1bfc6520e4b35b3e

I also tested the api responses now and could not find the discrepancy. It should be **pokemonID** everywhere.
So could please tell me where you are getting **pokemonId**?

**Comment by Aurel-Roci** [comment]
@swathi-ssunder  On the last 600 entries it is pokemonId. Also right before these 600 there are 7 entries the have no location coordinates.

**Comment by swathi-ssunder** [comment]
@Aurel-Roci - Thanks, found them. It should be fixed now.
Regarding the entries without location coordinates, they would be from Twitter,for which location is not available. 
@samitsv

**Comment by Aurel-Roci** [comment]
@swathi-ssunder Hey, sorry to bother again, but there is something else that is causing us some problems.
The json property order changes e.g.:

```
{
        "_id": "57c92ff6f0d1ffd702ba9641",
        "appearedOn": "2016-09-02T07:38:48.000Z",
        "pokemonID": 41,
        "source": "SKIPLAGGED",
        "__v": 0,
        "location": {
            "coordinates": [
                -84.242657,
                9.914319
            ],
            "type": "Point"
        }
    },
    {
        "_id": "57c930554e3bd9e102471781",
        "source": "TWITTER",
        "pokemonID": 1,
        "appearedOn": "2016-09-02T07:55:01.307Z",
        "__v": 0,
        "location": null
    },
```

Can you fix this?

**Comment by swathi-ssunder** [comment]
@Aurel-Roci - There is no need to be sorry:)

Will try to get this fixed. However, since it is JSON and not an array(where indices do matter), it shouldn't really matter from the point of view of accessing the data. 
Just curious to know how this affects !!

**Comment by jonas-he** [comment]
A JS Object is an "unordered set of key/value pairs". "You cannot and should not rely on the ordering of elements within a JSON object." http://stackoverflow.com/questions/3948206/json-order-mixed-up

**Comment by Aurel-Roci** [comment]
@swathi-ssunder Since we are converting this data into .arff if the order of the entries is different the program we are using for ML (Weka) will not open the file.

@jonas-he  I read when I was trying to fix the order on my part, but still I think you should be able to store the order of the fields, since for most of the part the order is the same.

**Comment by sacdallago** [comment]
Sorry for the super late jumpin, can you make it `pokemonId` with small `d`? The capital D doesn't make sense in camel-case :)
And yes, there's no ordering in the attributes inside an obj :) not even sure all values have all'attributes, that's why it's non-sql

**Comment by fabe85** [comment]
Just created a new branch called "pokemonIdRenaming" to make this fix.

**Comment by swathi-ssunder** [comment]
Code changes and also db migrations have been done.
@Aurel-Roci , @sacdallago - The field is now called **pokemonId**

Refer #113 and #114
