### ISSUE TITLE
PokemonSighting queries

### ISSUE THREAD

**Issue by MajorBreakfast** [PokemonGoers/PokeData#111]
Today, when I browsed through the JSON API documentation, I noticed that it is possible to query all PokemonSightings without a filter. I doubt that this will scale well. There should always be a limit on region and time. Currently it is also not possible to have both at once.

Here's an idea:
`/api/pokemon-sightings?rect=:tlLat,:tlLon,:brLat,brLon&time-span=:fromTime,:toTime`

`tl` = top left
`br` = bottom right
- `pokemon/sighting` -> `pokemon-sightings`
- Usage of query params
- Define time span by start and end time

---
- There should be a maximum for the area. Catch: The globe is round
- There should be a maximum duration

**Comment by jonas-he** [comment]
@MajorBreakfast we are aware of that issue and plan on implementing a limit or similiar.

**Comment by jonas-he** [comment]
Closed, see #119
