### ISSUE TITLE
Inconsistency of GetAllSightings response format

### ISSUE THREAD

**Issue by johartl** [PokemonGoers/PokeData#117]
**Request**

`curl http://pokedata.c4e3f8c7.svc.dockerapp.io:65014/api/pokemon/sighting/`

**Expected output**

``` javascript
{
    "message":"Success",
     "data": [
        { /*PokeSighting1*/ },
        { /*PokeSighting2*/ },
        // ...
    ]
}
```

**Actual output**

``` javascript
[
    { /*PokeSighting1*/ },
    { /*PokeSighting2*/ },
    // ...
]
```

The response contains the sighting objects directly rather than being wrapped in a `{ "message" :"Success", "data": [...] }` object.

**Comment by johartl** [comment]
The same holds true for the _GetAllPokemons_ route.

**Comment by swathi-ssunder** [comment]
See #118
