### ISSUE TITLE
Requirements for second phase

### ISSUE THREAD

**Issue by swathi-ssunder** [PokemonGoers/PokeData#120]
@sacdallago, @gyachdav  - We are working on the issues raised.
Meanwhile, we would like to know if there are any other specific requirements/expectations for the deadline on 7th September.

**Comment by sacdallago** [comment]
You can always come up with new data sources, but I believe that there will be requests from other groups, adjustments, bugs and improvements that need to be handled on what you have till now.

I will talk to the other mentors in these days and see if there's anything more specific :) but you are doing an excellent job guys ;)

**Comment by gyachdav** [comment]
Excellent job indeed!

I would like to see massive and continuous read-in from of all sources. I saw today that PokeRadar has summed up over 10M data points. How many sightings are currently stored in our API? **Of course the continuous scraping should only take place when the rostlab server is setup**. 

I will also like to see some statistics about the data you aggregated. This requirement is not in the original project description but having them would benefit our project immensely! Will specify some questions in a separate issue which i will reference here later.

**Comment by gyachdav** [comment]
#121
