### ISSUE TITLE
Statistics on aggregated data

### ISSUE THREAD

**Issue by gyachdav** [PokemonGoers/PokeData#121]
I played around with the data and started a google spreadsheet

https://docs.google.com/spreadsheets/d/1EFkw-_pS6G4rajmR85zqM1CBku2xxUQVoeECFU3cbWM/edit?usp=sharing

From the spread sheet you can see that there is a distinct correlation between CP and HP, but no pattern is found when trying to plot CP, weight and height. 

It would be interesting to see some statistics for (not an exhaustive list **more ideas encouraged**):
- [x] histogram of CPs/HPs
- [x] Histogram for # of attacks
- [x] Plot # of attacks vs CP
- [x] M/F/H/O distribution and CP/HP
- [x] Boxplots for CP/HP/weight/height
- [x] Top 10% of common weaknesses/resistance (histo)
- [x] Top 10% of common types

For sighting info:
- [ ] Total number of data points/daily average (global)/daily median average/DOW with highest number of sightings/DOW with lowest (also breakdown by data source)
- [ ] Table that lists 10 major urban centers and their daily average sighting 
- [ ] Table that list 10 exotic centers and their daily average sightings
- [x] Histogram for hourly sighting count (also per data source)
- [x] Histogram showing number of sighting per Pokemon (top 25%)

**Comment by gyachdav** [comment]
Assigning to @vivek-sethia so he can re-assign to appropriate team member.

**Comment by samitsv** [comment]
- added histogram of CPs/HPs

**Comment by fabe85** [comment]
https://docs.google.com/spreadsheets/d/1n93UaFEdUqtC7_nF-oK1hAPO2BJx-413PXAHC1uY2bU/edit?usp=sharing
google sheet for histogram of  # of attacks and # of attacks vs maxCP

**Comment by vivek-sethia** [comment]
@fabe85 the plot says that x-axis represents name but those are listed with numbers. So what does it stand for? Does y-axis stand for the count ? If yes then, why are there only 10 numbers on the x-axis?

**Comment by fabe85** [comment]
@vivek-sethia Oh sorry the axis labels are wrong. I will change that.

**Comment by fabe85** [comment]
google sheet for top 25% of pokemon sighting, major sighting sources, distribution of types, resistance and weakness
https://docs.google.com/spreadsheets/d/1mmy382caE5mCpKq021AhKawqvJCKB7UkBNfmSPJAsnQ/edit?usp=sharing

**Comment by jonas-he** [comment]
added diagrams from our presentation to the original spreadsheet from guy (click on "Sheet-2")

**Comment by gyachdav** [comment]
is this done?

**Comment by fabe85** [comment]
@gyachdav Basically it is done except the 10 major urban and exotic centers with their respective daily average sightings. This creates some problems to me. I will ask some other team members to help me with that but I am not sure if we can solve that. However, I think the main statistics are provided and they give a clear overview.

**Comment by fabe85** [comment]
Result: The remaining statistics cannot be generated only using the mlab databases. Therefore, I will close this issue now.
