### ISSUE TITLE
Data from Pokesniper

### ISSUE THREAD

**Issue by vivek-sethia** [PokemonGoers/PokeData#129]
@gyachdav @sacdallago @jonas-he  The `appearedOn` collected from `pokesniper` data source contains the time when the pokemon was last seen as opposed to other sources like pokeradar, pokecrew where it has the time when the pokemon actually spawned. As far as I know from some articles that the pokemon stays for 15 minutes at a place after spawning. So should I subtract 15 minutes from the time for the data from `pokesniper` or is there anything which I am missing?

Articles read : [1](https://www.reddit.com/r/TheSilphRoad/comments/4sryif/i_studied_pokemon_spawn_and_despawn_times_to_find/), [2](http://comicbook.com/2016/07/25/how-does-spawning-work-in-pokemon-go-/), [3](http://www.thebitbag.com/pokemon-go-nearby-long-pokemon-spawn-despawn-nearby-list/164068)

**Comment by sacdallago** [comment]
To me that sounds reasonable. I am still wondering how it is possible that they have an absolute init or terminal time

**Comment by jonas-he** [comment]
@vivek-sethia i am also subtracting 15 minutes for my sources if the specify something like `expire_At`

**Comment by jonas-he** [comment]
@sacdallago dont quite get your question. At one moment in time there are lets say thousands of pikachus all over the globe. And if they wouldnt expire then after some days everyone would know that theres a pikachu which would make it kind of boring.

**Comment by gyachdav** [comment]
@jonas-he that sounds reasonable in principal although time of sighting does not mean spawn+15, it's more like spawn + x | 0 &#8804; x &#8804; 15. not quite sure how we account for that. ideas?

**Comment by jonas-he** [comment]
@gyachdav most of the sites where we get the data from run scanners or base their predictions on scanners. Scanners are using reverse engineered API to Niantic servers and thus they deliver the exact data from the game, meaning either the exact spawn or despawn time.

**Comment by gyachdav** [comment]
Except for pokesniper which gives you sighting time? Can you cross reference between pokesniper and other sources? 

Btw, Using Niantic data may become a problem down the road.

**Comment by jonas-he** [comment]
@gyachdav No pokesnipers gives you the exact expire time. This is why we subtract 15 minutes from that to get the appearedOn time.
I checked this by looking at one entry from pokesnipers, then i run a scanner at this location (either through fastpokemap.se or on my own pc, see https://github.com/PokemonGoMap/PokemonGo-Map) and check if the time from pokesnipers is equal to the expire time given by the "illegal" source.

Well you can never be sure how these sources aquire their data, but for instance fastpokemap.se claims that it runs scanners, see https://fastpokemap.se/faq.html. Speculations:
https://www.reddit.com/r/pokemongodev/comments/4wgm1j/how_does_skiplagged_work/
https://www.reddit.com/r/pokemongodev/comments/51avwv/how_does_pokeradar_predict_the_spawns/

**Comment by vivek-sethia** [comment]
Done #132
