### ISSUE TITLE
Pokemon name/image in GetSightings methods

### ISSUE THREAD

**Issue by farisca** [PokemonGoers/PokeData#139]
Hello, I have a question regarding GetSightings\* methods. Since the number of sightings can be sometimes really huge, it would be quite slow to fetch data on that pokemon, for each of the sightings, in order to show its image on the map. Could you provide us with the link to the image (or at least the name of the pokemon) in the response to the GetSightings\* methods?

**Comment by jonas-he** [comment]
@farisca in every sighting you have a "pokemonId". When you have this id you simply have to put it in this URL http://pokedata.c4e3f8c7.svc.dockerapp.io:65014/api/pokemon/id/:id/icon
So for instance for a bulbasaur (id = 1) sighting you have to look up http://pokedata.c4e3f8c7.svc.dockerapp.io:65014/api/pokemon/id/1/icon

**Comment by farisca** [comment]
thanks for the explanation! :D
