### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by sacdallago** [PokemonGoers/PokeData#144]
Please update the readme a bit.
- [x] 1. Get rid of the introduction, it was just a placeholder
- [x] 2. Describe what this project is about, contributors, where the demo is running, prerequisites...
- [x] 3. Describe how to use it (fetching from docker directly or building from the repo)
- [x] 4. Describe how to run the listeners
- [x] 5. Where is the config? How can I define stuff? What if I don't wanna use docker?

**Comment by samitsv** [comment]
updating read me https://github.com/PokemonGoers/PokeData/tree/updateReadme

**Comment by jonas-he** [comment]
see #151
