### ISSUE TITLE
Gym position

### ISSUE THREAD

**Issue by marwage** [PokemonGoers/PokeData#153]
Can you please add the positions of gyms to the data dump?

**Comment by jonas-he** [comment]
@marwage 
1. which data dump?
2. we currently don't gather infos about gyms, the only data set with gym info is the one i provided you here https://github.com/PokemonGoers/PredictPokemon-2/issues/38

**Comment by marwage** [comment]
@Aurel-Roci @MatthiasBaur @bensLine @semioniy

**Comment by bensLine** [comment]
@jonas-he yes, we meant the data from the dump you provided. Anyway if you do not use the positions so for we take care of that by ourself.
