### ISSUE TITLE
Empty API result

### ISSUE THREAD

**Issue by johartl** [PokemonGoers/PokeData#154]
It seems like all API requests now return an empty `data` object.
E.g. `curl http://pokedata.c4e3f8c7.svc.dockerapp.io:65014/api/pokemon/`

``` (json)
{
    "message": "Success",
    "data": []
}
```

**Comment by jonas-he** [comment]
@johartl we are currently rebuilding DB, so at the moment the collection for the pokemon is empty.
But should be fixed soon (or maybe not because we exceeded the storage limit on the DB provider 😄)

**Comment by johartl** [comment]
Do you know when you will be done with this approximately?
Thanks for the prompt response.

**Comment by sacdallago** [comment]
I've just stopped the scrapers since they are just interfering with your work, I guess.

**Comment by jonas-he** [comment]
@johartl fixed

**Comment by jonas-he** [comment]
@sacdallago when did you stop the scrapers? because there was no more data written to mlab since like the evening on the day you started them (aka Wednesday)

**Comment by sacdallago** [comment]
Mh. I stopped then when I commented earlier. Probably once the database rises an error the scrapers stop without dying (they enter in the so called zombie-state), aka the docker container didn't restart (it only restarts on non-exit 0) and was just running on empty?

Might be worth checking, could you open an issue for this?

**Comment by jonas-he** [comment]
@sacdallago i think the fact that there was no more data inserted is more related to the mlab limit
