### ISSUE TITLE
Create release

### ISSUE THREAD

**Issue by sacdallago** [PokemonGoers/PokeData#159]
Create tag + release + push to master.

I will manually start the scrapers on master from the evil rostlab machine

**Comment by samitsv** [comment]
@sacdallago this will have to wait since after seminar we had a discussion with haspokemongo #140  so we will try to integrate our works and then we can proceed with releasing

**Comment by sacdallago** [comment]
@samitsv you can create a pre-release. I need this to populate the docker `:latest` autobuild

**Comment by swathi-ssunder** [comment]
@sacdallago - Here is the link to the [pre-release](https://github.com/PokemonGoers/PokeData/releases/tag/v1.0-alpha).
We plan to create the release after integration with the other project.

**Comment by sacdallago** [comment]
Needed to trigger this to run the scrapers
