### ISSUE TITLE
Additional data: More images / image formats

### ISSUE THREAD

**Issue by AlexanderLill** [PokemonGoers/PokeData#160]
Hello everyone,

it would be very helpful to receive some more different image formats per pokemon for our website / app. We are talking mainly about different formats, and not necessarily different content of the images :)

Particularly the following would be helpful:
- small, not animated (80x80 pixels) (like the one now, just without animation)
- big, not animated (min 512x512 pixels, ... svg?, vectorgrafic), png with transparency

If there are any questions feel free to ask, the ones without animation are the most important right now I think ( @johartl )

**Comment by jonas-he** [comment]
what about these for the big ones with transparency: http://nintendo.wikia.com/wiki/Category:First_generation_Pok%C3%A9mon_images
We have to make sure they are under a free license right? Dont know about these ones ...

**Comment by AlexanderLill** [comment]
> The Service includes access to audio and/or visual content (including videos, photographs, music, graphics, logos, etc.), which has been licensed for use and exhibition herein from third parties (“Media Content”). Such Media Content may be accessible via a player embedded on the Site, which links to and plays content hosted on other sites or services (“Media Player”).
> Without limiting the application of any other terms of this Agreement, **you also agree that you will not do, or attempt to do, any of the following**:
> 
> attempt to download, redistribute, alter, delete, or insert advertising or promotional materials within any Media Content or in connection with any Media Player;
> use any Media Content or Media Player for any purpose other than non-commercial, personal consumption and viewing such Media Content;
> attempt to circumvent, disable or otherwise interfere with security-related features of the Service or any Media Player, including any features that prevent or restrict use or copying of any Media Content;
> attempt to modify, enhance, edit, translate, adapt, alter, reverse engineer, decompile, disassemble, or **create derivative works based upon any Media Player or Media Content**;
> attempt to license, transfer, convey or assign to any third party any rights to use or exhibit any Media Player or Media Content , including to market, promote, display, re-distribute or re-transmit any Media Player or Media Content;
> **reformat, optimize or customize any Media Player or Media Content for display, distribution or transmission via any platforms, protocols or delivery mechanisms other than as expressly permitted by and within the Services**;

@jonas-he maybe we find another source, or we ask them in a mail if it's okay for us to use them non-commercially? ( @gyachdav )

**Comment by jonas-he** [comment]
@AlexanderLill for these images it says they have the copyright of Nintendo but they can be used under "fair use" (e.g. http://nintendo.wikia.com/wiki/File:Tauros.png). As wikia.com is not related to Nintendo and use these images and apparently dont have problems with Nintendo I think we might use them as well. However I don't want to have the last word on this @gyachdav

**Comment by jonas-he** [comment]
another source, also fair use: https://github.com/jnovack/pokemon-svg

**Comment by jonas-he** [comment]
@Lugitan maybe you want to join in on the conversation and give a status update if you have one.

**Comment by samitsv** [comment]
@jonas-he I had a discussion with @Lugitan as well in the morning so using it should be fine using the images, and giving nintendo and the source credits. I will be using the existing gif and png images from http://veekun.com/dex/downloads, svgs from https://github.com/jnovack/pokemon-svg/tree/master/svg, this should cover all the requred images

**Comment by samitsv** [comment]
@sacdallago now i want to add svg,png and gif images to my pokemonicons collection in mlab and i am not able to because of quota, what should i do? required for supporting new image requirements

**Comment by samitsv** [comment]
- closed in https://github.com/PokemonGoers/PokeData/pull/165
- http://pokedata.c4e3f8c7.svc.dockerapp.io:65014/doc/

**Comment by samitsv** [comment]
but there might be some missing images on request(due to our mlab database limitation), but will be udpated

**Comment by jonas-he** [comment]
@samitsv yeah there are some missing (there are 106 out of 151). I would delete some of the 2,5 million sightings and maybe you can insert it again.

**Comment by sacdallago** [comment]
@samitsv  the RostLab mongo machine is accessible only from the RostLab server wich will hold the app, at some stage. Meaning: I don't have a fix to the mlab quota problem, not for development, at least. For production, yes.
