### ISSUE TITLE
Additional data: Rarity of pokemon

### ISSUE THREAD

**Issue by AlexanderLill** [PokemonGoers/PokeData#163]
Hello everyone,

it would be very helpful to also get the data about the rarity of each pokemon. We want to use this for sorting pokemon in different places and also to show some indicator in our PokeDex.

The following fields are therefore useful:
**ranking**: the number indicating which number this pokemon gets on a ranking from 1: rarest pokemon to 151: most often occurring pokemon. _E.g. as far as I remember pidgey would be nr 151 here_

**appearance_likelihood**: percentage of this pokemon of all pokemons, e.g. _20% of all appearing pokemon are pidgey_

If there are any questions please let us know :)
( @johartl )

Best,
Alex

**Comment by jonas-he** [comment]
@AlexanderLill There are already a lot of such rankings floating around the web, e.g. http://imgur.com/gallery/ZTgIu or https://docs.google.com/document/d/1iZeW3wt-h-L7v97FaDLSjqxFysTLQef92c1nNOqt3Tk
but we could also use our own analysis data. I will check what makes more sense.
Do you also want an API route for that or shall we provide it to you as an excel sheet/json or sth else?

**Comment by johartl** [comment]
It would be nice if you could add the data to the pokemon object itself.

``` (javascript)
{
  "pokemonId": 25,
  "name": "Pikachu",
  ...
  "ranking": 42,
  "appearanceLikelihood": 0.04
}
```

**Comment by sacdallago** [comment]
Mh. these data should come from the @PokemonGoers/predictpokemon-1 @PokemonGoers/predictpokemon-2 groups, though I wonder how. @goldbergtatyana can you get this kind of information out of the ML device itself? And how.. 💭

**Comment by semioniy** [comment]
@sacdallago we have the distribution of pokemon seen, it is only an approximation of rarity, but still. 
![distr](https://cloud.githubusercontent.com/assets/21012972/18815105/bf0bd6d6-8326-11e6-844f-4660e8691455.jpg)![distr2](https://cloud.githubusercontent.com/assets/21012972/18815119/25bbb70c-8327-11e6-944f-c1f73d6dce58.jpg)
But with 500k dataset it seems to be pretty legit to me. (The pictures are only from 50k dataset though)

**Comment by sacdallago** [comment]
yeah :) I get that, but eventually the numbers will adjust?

**Comment by semioniy** [comment]
I think so.

**Comment by bensLine** [comment]
@sacdallago from the 600k data dump we get those numbers for the different pokemon ids
- 1: 2725
- 2: 170
- 3: 24
- 4: 1220
- 5: 40
- 6: 13
- 7: 3157
- 8: 179
- 9: 37
- 10: 20039
- 11: 1283
- 12: 160
- 13: 56695
- 14: 3648
- 15: 445
- 16: 104627
- 17: 6497
- 18: 870
- 19: 78040
- 20: 2451
- 21: 25032
- 22: 832
- 23: 8108
- 24: 279
- 25: 1017
- 26: 20
- 27: 3672
- 28: 123
- 29: 7964
- 30: 446
- 31: 36
- 32: 8619
- 33: 519
- 34: 45
- 35: 7595
- 36: 130
- 37: 1099
- 38: 21
- 39: 2283
- 40: 45
- 41: 21212
- 42: 2247
- 43: 7081
- 44: 457
- 45: 37
- 46: 14248
- 47: 470
- 48: 16475
- 49: 484
- 50: 1492
- 51: 51
- 52: 3610
- 53: 71
- 54: 8298
- 55: 272
- 56: 3529
- 57: 113
- 58: 3400
- 59: 60
- 60: 8042
- 61: 533
- 62: 34
- 63: 2660
- 64: 194
- 65: 18
- 66: 1226
- 67: 79
- 68: 5
- 69: 6996
- 70: 436
- 71: 40
- 72: 2290
- 73: 285
- 74: 4540
- 75: 279
- 76: 26
- 77: 2192
- 78: 66
- 79: 3753
- 80: 126
- 81: 2085
- 82: 65
- 83: 8
- 84: 1134
- 85: 583
- 86: 1474
- 87: 60
- 88: 270
- 89: 10
- 90: 2855
- 91: 62
- 92: 5135
- 93: 306
- 94: 20
- 95: 380
- 96: 22081
- 97: 678
- 98: 9547
- 99: 301
- 100: 2047
- 101: 58
- 102: 3346
- 103: 50
- 104: 1771
- 105: 58
- 106: 97
- 107: 83
- 108: 113
- 109: 1197
- 110: 35
- 111: 2239
- 112: 97
- 113: 44
- 114: 665
- 115: 67
- 116: 4952
- 117: 165
- 118: 8032
- 119: 307
- 120: 7412
- 121: 117
- 122: 762
- 123: 655
- 124: 1538
- 125: 291
- 126: 403
- 127: 2836
- 128: 1337
- 129: 16580
- 130: 14
- 131: 37
- 133: 23600
- 134: 56
- 135: 30
- 136: 33
- 137: 34
- 138: 507
- 139: 15
- 140: 524
- 141: 7
- 142: 65
- 143: 139
- 147: 1190
- 148: 86
- 149: 50

I guess we could calculate representative percentages from that. However, I thought there should also be a pokemon grouping like `rare, common, not-you-again`. Am I mixing things up or was that the same?

**Comment by jonas-he** [comment]
done, see #171

**Comment by AlexanderLill** [comment]
@jonas-he thanks, great! :)
@bensLine I think we will have to come up with a visualisation in the user interface, yes. I think we will somehow map the rarity ranks to a star-system (1 to 3 stars) or something, let's see. If someone is interested in brainstorming => https://github.com/PokemonGoers/Catch-em-all/issues/86

PS: It would be cool if the API documentation could be updated too so we have a quick overview over the available attributes
