### ISSUE TITLE
API unavailable after integration with project C

### ISSUE THREAD

**Issue by swathi-ssunder** [PokemonGoers/PokeData#167]
@sacdallago - After #162 , the [API](http://pokedata.c4e3f8c7.svc.dockerapp.io:65014/api/pokemon) link is not available.
The builds (both Travis and Docker) seemed fine and completed without errors.

**Comment by jonas-he** [comment]
@swathi-ssunder it seems that DNS resolution is not working. This is the case for everything like *dockerapp.io and it seems that this appears from time to time, see https://forums.docker.com/t/resolved-dockerapp-io-dns-down/18448
So nothing we can do about right now.

**Comment by swathi-ssunder** [comment]
@sockeqwe Not related to this issue, however could you look at https://github.com/PokemonGoers/PokeData/pull/162#issuecomment-249376379 ?

**Comment by swathi-ssunder** [comment]
Seems to be fixed after #169

**Comment by sacdallago** [comment]
Sorry for just reading now, connection is crap. Now slowly going through all the issues in my 10 min hotel WiFi :D
