### ISSUE TITLE
Preliminary results

### ISSUE THREAD

**Issue by gyachdav** [PokemonGoers/PokeData#17]
Dear Project A members,

Since the deliverables from this group are so critical for the success of all other projects, we are setting a deadline to get some preliminary results from your group. 

The soft  deadline is August 31st and the hard deadline is August 7th.

By the deadline we want to see an active API that makes data you scraped available. You will have a database in place and will already have two data sources populate this database. 

Keep in mind that this milestone is set to make sure that we get data to projects that are waiting for it downstream. You are welcome to make changes to the db structure after the deadline and extend the API (keep the main schema of the API in place though, others will rely on it staying stable).  

Let me know if you have any questions. 

Cheers, 
Guy

**Comment by jonas-he** [comment]
You mean "hard deadline is September 7th" ?

**Comment by gyachdav** [comment]
Yes Sep 7th. Thanks for catching this mistake. LMK if you have any questions.

**Comment by samitsv** [comment]
Hello tutors,
   I think we are missing a team member. Is there any info if he/she will
be joing the group?

**Comment by gyachdav** [comment]
How many people are you so far. There suppose to be 6 students assigned to this project.

**Comment by swathi-ssunder** [comment]
We are 5 so far. Annette Köhler has also been assigned to Group A as per the website. But we have not heard from her so far.

**Comment by gyachdav** [comment]
Hi Anette,

Your group is looking for you ;)

**Comment by swathi-ssunder** [comment]
It seems she is not a member of this repository too.

**Comment by goldbergtatyana** [comment]
We pinged Annette to get in touch with you asap. But please do not wait for her, continue contributing. Annette will then just join it in the middle.

**Comment by swathi-ssunder** [comment]
The results of the preliminary phase can be found [here](http://pokedata.c4e3f8c7.svc.dockerapp.io:65014/doc/).
