### ISSUE TITLE
Pokemon icons

### ISSUE THREAD

**Issue by gqinami** [PokemonGoers/PokeData#172]
Hey guys,

It looks like there is a problem with the API for pokemon icons (gifs). For most of the pokemons, the icons are not available:

![image](https://cloud.githubusercontent.com/assets/15110315/18840405/c8795eda-840e-11e6-82fc-37a78df93f0f.png)

Can you please check this?

Thanks

**Comment by samitsv** [comment]
yes, this is a problem for a while since we are running out of space in our temporary db in mlab. this will be solved soon when we use the rostlab db

**Comment by jonas-he** [comment]
@gqinami its fixed now
