### ISSUE TITLE
Wrong/shifted description texts

### ISSUE THREAD

**Issue by AlexanderLill** [PokemonGoers/PokeData#173]
Hello everybody,

call me crazy, but I think I just found a strange issue: As far as I see the descriptions are somehow shifted starting at pokemon 20: Raticate.

It starts with 19: Rattata not even having a `description` field:
http://pokedata.c4e3f8c7.svc.dockerapp.io:65014/api/pokemon/id/19

And then goes on with pokemon 20-22 having the description of the pokemon right before them:
http://pokedata.c4e3f8c7.svc.dockerapp.io:65014/api/pokemon/id/20
http://pokedata.c4e3f8c7.svc.dockerapp.io:65014/api/pokemon/id/21
http://pokedata.c4e3f8c7.svc.dockerapp.io:65014/api/pokemon/id/22

It seems to be alright again at pokemon 23:
http://pokedata.c4e3f8c7.svc.dockerapp.io:65014/api/pokemon/id/23

It would be really nice if this could be fixed. This problem seems to occur only for pokemon 19-22 - but of course I did not check all of them ;) Maybe you can do some selected checks, and also see if any other field might be shifted/wrong somehow.

PS: I found a not-documented field `Next Evolution Requirements` in some of the pokemon, which sounds interesting :)

@PokemonGoers/catch-em-all

**Comment by swathi-ssunder** [comment]
@AlexanderLill - Thanks for the observation. 
There was indeed a problem with the description and I fixed it in the database as well as the json file. Refer #174.
Also checked the description for all other pokemons and they seem fine.

**Comment by AlexanderLill** [comment]
Thanks :)
