### ISSUE TITLE
New API route

### ISSUE THREAD

**Issue by gqinami** [PokemonGoers/PokeData#178]
Hello @PokemonGoers/pokedata,

As per the requirements, we need to have a filter function that will get some data from the database, based on the filter criteria.

The filter criteria is: 
- Pokemon IDs (Array of pokemon IDs),
- Sightings since (date object or seconds), 
- Predictions until (date object or seconds). 

So basically, we would like to get all pokemons that match this criteria. There are two options, either you make two api routes, one for sightings and one for predictions, or you can give us one and we get all sightings and predictions at the same time (we prefer the second option).

Please let us know if you would need more information, and also confirm us on the things that are optional (i.e. date object or seconds; and one api route vs two). 

Best,
PokeMap-1

**Comment by gyachdav** [comment]
@gqinami this is a bit too late in the process don't you think? you're already suppose to wrap up this week. Also this is not really an issue but more of a draft requirement. If you want project A to cooperate you better give them concise info of what you need and how to execute. Asking them to come up with design and implementation decision at this stage will not fly. I'm closing this issue and expect you come up with a better more serious approach.
