### ISSUE TITLE
Receive sightings in time range

### ISSUE THREAD

**Issue by bensLine** [PokemonGoers/PokeData#184]
Hey guys,

I tried to receive data from the API for 1 day at a given timestamp but I do not get any results.
http://pokedata.c4e3f8c7.svc.dockerapp.io:65014/api/pokemon/sighting/ts/1474702424000/range/1d

`{"message":"Failure. No sighting details within this time range exists!","limited":false,"data":"Cast to date failed for value \"Invalid Date\" at path \"appearedOn\""}`

I tried it for different timestamps and ranges. Am I doing something wrong? The docu says timestamp should be UTC.

**Comment by vivek-sethia** [comment]
http://pokedata.c4e3f8c7.svc.dockerapp.io:65014/api/pokemon/sighting/ts/14%20September%202016%2000:00:00/range/1w

http://pokedata.c4e3f8c7.svc.dockerapp.io:65014/api/pokemon/sighting/ts/2016-09-14T08:00:00/range/1w 

Both of the above url works, anything that is accepted by `new Date` can be used. I will update doc since internally we are converting it into UTC.

**Comment by bensLine** [comment]
sweet, thanks! :)

**Comment by bensLine** [comment]
One more question, there is no data yet for the last week:
http://pokedata.c4e3f8c7.svc.dockerapp.io:65014/api/pokemon/sighting/ts/2016-10-14T16:22:34.648Z/range/1w
what's the latest data from when I can receive data?

**Comment by bensLine** [comment]
and is there a limitation that the API returns max 1k data points? cause we need more than 10k :p

**Comment by jonas-he** [comment]
@bensLine the latest data is from around 24th of septembre. Please note that the data there is not really thought to be something to work with. If you want nice and consistent data ask @sacdallago (im thinking of the 6GB thing).

**Comment by sacdallago** [comment]
AWS banned us :D we are fighting via fax to get the damn account up

**Comment by jonas-he** [comment]
@sacdallago for what did they ban us ?

**Comment by sacdallago** [comment]
They want to verify that we are human beings, and this is done via FAX!!!! Like: hello? 1950's calling?

So: we are still waiting.
