### ISSUE TITLE
No tweet data from the api

### ISSUE THREAD

**Issue by mfkaptan** [PokemonGoers/PokeData#189]
Hi guys,

Catch-em-all here. I am trying to get tweets (with actual texts) from the api for tweet view on our app. Can anybody tell me what is the reason http://pokedata.c4e3f8c7.svc.dockerapp.io:65014/api/pokemon/sighting/source/twitter returns

```
{
    "message": "Success",
    "limited": false,
    "data": []
}
```

Also, will this result contain the text data?

Thanks,
@mfkaptan

**Comment by jonas-he** [comment]
@mfkaptan the reason is that there are no sightings from twitter currently in our (temporary) database. There won't be any text, it would look the same like these ones http://pokedata.c4e3f8c7.svc.dockerapp.io:65014/api/pokemon/sighting

**Comment by sacdallago** [comment]
and now ( #190 ) the most likely source seems to be twitter :D :D :D crowd sourcing findings.

Actually. I see a **huge potential** here: with respect to everyone else, we have a WORKING solution to extract sightings from twitter. Today. No one else can do that. And while other services try to crack the new security measures, we can show data by crowd sourcing.

@gyachdav @goldbergtatyana 

Now it would be the best time for AWS to let us use their damn services.

**Comment by mfkaptan** [comment]
@jonas-he Thanks for the answer. So, we won't keep any text from twitter in the database, is that correct (also no tweet data for the mobs)?

**Comment by jonas-he** [comment]
@mfkaptan yes that is correct. Regarding the mobs im not quite sure, please ask the hashPokemonGo team.
