### ISSUE TITLE
status of scraper/listener

### ISSUE THREAD

**Issue by jonas-he** [PokemonGoers/PokeData#190]
As Niantic has recently enforced an update to the API of their game (implemented some new security/ anti reverse engineering features) all websites that worked with actual game data are out of service as of now.

If it is the plan that our listeners will be used in the future then i guess that theres little hope that they will work. The owner of fastpokemap is currently working on breaking the API, but he said that he will not release how to do that. Apart from that we could still scrape crowd-sourced websites (which sadly i cant find any reliable one atm).

**Comment by sacdallago** [comment]
thanks for the heads up @jonas-he , this sucks! It's good though, that the prediction guys have had enough data to come up with predictions that exceed random. Hopefully Niantic won't change the approach on that alg though :cry:

**Comment by goldbergtatyana** [comment]
and if they will, we'll just retrain our machin learner 👍

**Comment by MatthiasBaur** [comment]
Actually we won't be able to preform on a modified spawning algorithm without contemporary data on it. But since most of Niantics effort seems to go into rooting out 3rd parties' sites, I believe that won't be for some time.

**Comment by sacdallago** [comment]
Yup. Where's the fun for developers Niantics, WHERE?! :D
