### ISSUE TITLE
Determination of features for extraction, to be used later in the Machine Learning Algorithm + Consulting PokemonGo expert for more features

### ISSUE THREAD

**Issue by samitsv** [PokemonGoers/PokeData#2]

**Comment by samitsv** [comment]
**Important Features:**
1.  Correlation between the **Type** of pokemon and the **environment/location/time**:
     for example: water type pokemon should be correlated with environments locations near water resources, grass type with grassy/forest areas, dark/ghost pokemons to be found more during the night time

**Comment by jonas-he** [comment]
So basically all the data sources we have found do provide pokemonId (1 = Bulbasaur, ...) location and time and no more useful information. To get the type of a specific Pokemon we can use the data we will extract from a wiki (For Bulbasaur it would be Grass/Poison). To get the environment the pokemon spawned in we have to come up with a function that takes location (lat/long) as input and returns something like grassland: 70%, water: 50%, desert: 0%. For a possible solution refer to: http://gis.stackexchange.com/questions/181659/api-for-land-use-land-cover

**Comment by fabe85** [comment]
Well the idea is good but the link only covers places of the United States.
In pokeapi.co there is an entry called "location_area_encounters". So maybe we can use that.

**Comment by sacdallago** [comment]
I also like the idea a lot! Maybe using open street map data (POIs and what not) you can figure out the rest of the globe?
There is enough data out there to complete the task :)

**Comment by jonas-he** [comment]
@fabe85 I think pokeapi.co is for the main game series and not specifically for PokemonGo, so not useful here.
As all the APIs i could find were limited to USA or Europe, i searched for a global thing.
I found the this map http://glcf.umd.edu/data/lc/ which has a resolution of about 10km (the 5' x 5' one) and can be downloaded from a ftp server (unzipped its about 20MB). If this resolution is to low, theres this here http://due.esrin.esa.int/page_globcover.php with 300m resolution and about 300MB in size. Regardless of the map one would have to write a program that extracts the land/environment information for a given lat/long pair...

**Comment by jonas-he** [comment]
another approuch would be to use the Google Static Maps API and to do some image processing (count green/blue/... amount) on the picture.
http://maps.googleapis.com/maps/api/staticmap?center=48.0881292,11.8356075&zoom=12&format=png&sensor=false&scale=2&size=640x480&maptype=roadmap&style=visibility:off&style=feature:water%7Celement:geometry%7Cvisibility:simplified&style=feature:poi.park%7Celement:geometry%7Cvisibility:on&style=feature:landscape.natural%7Celement:geometry%7Cvisibility:on

**Comment by jonas-he** [comment]
since the time value we extract (e.g from pokeradar) is in unix time (milliseconds since 1/1/1970, 00:00 UTC) we don't represent the time of the day at this given location in our data (but this is important since some pokemon spawn more often during night time). So i would suggest to have 'absoluteTime' (unix time) and 'relativeTime' (e.g. 3 pm) as features.

**Comment by sacdallago** [comment]
@jonas-he very good observation! Time+loc = AM/PM is indeed an important aspect. I believe though that the ML device should be able/learn to discriminate between day time and night time using geolocation + absolute time by itself.
In my personal view adding PM/AM as a feature might be redundant, even worsen the score of the prediction (or not contribute).

Thoughts on that @goldbergtatyana ?

**Comment by goldbergtatyana** [comment]
for ML we would translate AM/PM in the corresponding 24h format. So anything is good. 

Good job @jonas-he on spotting that :+1:

**Comment by jonas-he** [comment]
@sacdallago I was thinking the same sort of. Since AM/PM can be represented as a function of absoluteTime and location we're not really adding new information. But maybe the ML will figure out the patterns faster when given this additional feature. And as I heard: "The more data the better" regarding the ML.

**Comment by sacdallago** [comment]
Who told you that @jonas-he ? :D
So, let me expand on the "the more data the better" claim:
More data is good, but too much [unrelated, redundant] data is bad. Why?
First: you have to train your model, and the more data or combinations of features you have to try, the more time it takes (computationally speaking).
Second: sometimes obtaining data is a long process (time, energy), and if the final contribution to the prediction is irrelevant, it is a big deal of time and energy wasted.

It is not the case here, but this I would use as a general rule of thumb. You always better sit down a moment and think about feasibility :)

Back to your specific problem again: yup. I don't have **the** answer. It seems to me that it should get it on its own, but producing this data is straightforward and testing it also, so throw it in and let's see if it leads somewhere :)

**Comment by jonas-he** [comment]
I was told by @vivek-sethia because he took part in the ML introduction by @goldbergtatyana :smile: 
Ok we'll add this feature :)

**Comment by vivek-sethia** [comment]
@jonas-he  I mean that in the context of finding more features rather than restricting it by some self-assumption, that's what I understood from the class :-). Hope I didnt get it wrong @goldbergtatyana .

**Comment by sacdallago** [comment]
You got it right @vivek-sethia , and also @jonas-he didn't say anything wrong :) I was just expanding on that catch-phrase with what I have learned so far :wink:
As I said, what I was explaining doesn't really apply to this case, it's just for you to remember in an industry-like setting or in cases where access to the data is super difficult or the complexity of the data blows up exponentially :) In some cases though blowing up complexity actually helps the prediction, you never know (if we did, we wouldn't need ML), but then it's feasibility that comes into the game again :D

So many things to keep in mind in this life :laughing:

**Comment by samitsv** [comment]
#50 we have created a common schema for our database from where all the features required can be accessed
