### ISSUE TITLE
Shared database instance

### ISSUE THREAD

**Issue by sacdallago** [PokemonGoers/PokeData#20]
Dear members of project A,
I see you have already started to set up mongoose, good job.

At some stage it will be useful for you to have a shared database, so that everyone sees the same data.
You can get a free 500MB database at [mlab](https://mlab.com/).

**PLEASE** remember that the connection details for Read+Write users should **NOT** be copied in any file that will be uploaded to github!!!!!!

A further suggestion follows in the next issue.

**Comment by swathi-ssunder** [comment]
Data can now be stored either on a local database or a shared database based on the configuration parameter.
Refer #26 .
Awaiting further suggestions.
