### ISSUE TITLE
Data for pokemon's info page 

### ISSUE THREAD

**Issue by gyachdav** [PokemonGoers/PokeData#30]
Information to collect on each Pokemon(info will appear on pokemon's info page):
- name
- gender (note that there's one Pokemon Nidoran) that can be both boy or girl)
- height
- weight 
- category (kicking, hypnotize)
- ability/moves
- type
- weakeness
- evolution and pre form (note that a Pokemon can evolve into several forms)

**Comment by fabe85** [comment]
What is meant by weakness?
When looking at http://www.pokemongoevolution.com/ there is always only one evolution form.

**Comment by jonas-he** [comment]
i think weakness means if your pokemon is not very effective when fighting against another.
In the table here: http://onlinefanatic.com/pokemon-go-strength-and-weakness-chart/ you can see that for the red field the damage gets multiplied by 0.8 so e.g. if a NORMAL pokemon attacks a ROCK pokemon it is not very effective.

**Comment by fabe85** [comment]
Ok then we should also add the strength feature. But I'm not sure how to save these data because we need an array of each type with the specific weakness and strength but we don't know the type beforehand.

**Comment by gyachdav** [comment]
@fabe85 note that Eevee can evolve into [three forms](https://en.wikipedia.org/wiki/Eevee#Evolution) and not one. you will need to define a one to many relationship in your model.

**Comment by gyachdav** [comment]
Weakness means which type this Pokemon has a weakness to during gym battles. See http://bulbapedia.bulbagarden.net/wiki/Onix_(Pok%C3%A9mon)#Pok.C3.A9dex_entries and search for `Weak to:` on the page.

**Comment by fabe85** [comment]
Right now we have a complete list of these features in json format. It is only some work to do about filling the database because in this very moment we use a somewhat outdated schema.
