### ISSUE TITLE
Use env variables rather than config variables

### ISSUE THREAD

**Issue by swathi-ssunder** [PokemonGoers/PokeData#43]
Refer https://github.com/PokemonGoers/PokeData/pull/26#issuecomment-240594260

Eg: For distinguishing between shared and local db

**Comment by swathi-ssunder** [comment]
@vivek-sethia Can you pull 'env-db' branch and test it? If everything is working fine, then I will raise a pull request. 
I have also created a separate service for database and used in the other files.

**Comment by vivek-sethia** [comment]
@swathi-ssunder It works fine, you can raise a pull request.

**Comment by sacdallago** [comment]
:D I just talked about this in #21

**Comment by swathi-ssunder** [comment]
@sacdallago - Sorry, but I didn't quite get the relation of the comments in #21 to this issue.
I would be obliged if you could clarify this.

**Comment by sacdallago** [comment]
@swathi-ssunder nothing too important ;)

> Also: I'm missing still data in the ENV file, like database credentials for production (which is probably why I cannot get / ?) [https://github.com/PokemonGoers/PokeData/issues/21#issuecomment-241981144]

**Comment by swathi-ssunder** [comment]
@sacdallago It seems like this issue can be closed as the changes have been made. Hence closing this issue
