### ISSUE TITLE
Represent latitude/longitude in standard format

### ISSUE THREAD

**Issue by swathi-ssunder** [PokemonGoers/PokeData#51]
Refer https://github.com/PokemonGoers/PokeData/pull/48#issuecomment-241354821 
Eg:  http://geojson.org

**Comment by sacdallago** [comment]
Nice :)

**Comment by fabe85** [comment]
Right now all seems to be working in terms of geojson so we decided to close this issue. If we come up later with some problems we open another issue (confer also #50)
