### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by sacdallago** [PokemonGoers/PokeData#59]
Hey guys, i just came across this one example: https://github.com/PokemonGoers/PokeData/blob/develop/scripts/listen.js#L21

In the cases where the callback ends (either by calling an async function, or another callback) it is good practice to `return` the last executed LOC :)

Just keep this rule of thumb in your head: if I'm writing a function, i need to define a return.

In many cases it doesn't change too much, but it highers readability and in some cases it stops unnecessary execution of code ;)

**Comment by vivek-sethia** [comment]
I will ensure this for future commits.
