### ISSUE TITLE
Set up a document-oriented database (DB) + Set up an API server that will expose the data to all the downstream apps that will consume it

### ISSUE THREAD

**Issue by vivek-sethia** [PokemonGoers/PokeData#6]

**Comment by sacdallago** [comment]
This issue sounds like a milestone to me. Keep issues smaller and separate them ;)

**Comment by swathi-ssunder** [comment]
Sure, we actually added milestones too, but did not separate the issues !
Will consider your comment about issues and make changes accordingly.
