### ISSUE TITLE
Data extraction - PokemonGo Wiki - Design Strategy for extraction

### ISSUE THREAD

**Issue by swathi-ssunder** [PokemonGoers/PokeData#7]

**Comment by swathi-ssunder** [comment]
1. For extraction from [PokemonGo Wiki](https://pkmngowiki.com/wiki/Pok%C3%A9mon), we will need to scrape the web-site.
   Is this okay or should we limit ourselves to data extraction only from APIs?
2. Also, some of the data present in the Wiki is also available through some other APIs. (This question is also applicable to other data sources.) So, should we also extract from here, so that we can still populate the DB with these fields in case of unavailability of other sources?

**Comment by gyachdav** [comment]
1. Yes extracting from the API is preferable. If there's data item that can only be fetched From free text then please confirm with us your strategy. 

2: combining several APIs to get better coverage is a good idea. But you need to take care that the data remains consistent across the different sources. If there are conflicts you will need to resolve them. For instance keep in mind that there are several generations of pokemons so there may be inconsistencies.

**Comment by vivek-sethia** [comment]
Not required since we are extracting it from other sources.
