### ISSUE TITLE
Feature list and and initial data set

### ISSUE THREAD

**Issue by bensLine** [PokemonGoers/PokeData#71]
Hey @PokemonGoers/pokedata ,

we from @PokemonGoers/predictpokemon-2  were wondering if you can provide us with a list of all currently implemented features that you collect for a database entry, e.g. 
`PokemonId, lat, lon, timestamp, ...`

Furthermore, it would be great if you can provide us an initial data set with those features. Currently we use the dummy data set which only provides distinct data for _PokemonId, lat, lon, timestamp_ but I guess you have already more data, which could helps us in implementing the classifier.

Cheers,
Benni

**Comment by samitsv** [comment]
Right now we have a main database where we store data collected from different sources, the features in he database are **source,location, pokemonId, appearedOn** 
- source: from where the data is collected(e.g. TWITTER, POKERADAR, POKESNIPER)
- location: the coordinates of appearance
- pokemonId: id of the pokemon
- appearedOn: the date and time when the pokemon appeared( (or tweet date in case of twitter)
- regarding initial data set we are working on it, and will provide it soon

**Comment by swathi-ssunder** [comment]
@bensLine We are working on the API, using which you will be able to access all the data we have extracted so far. 
We will update this issue once the API is up. This should be done latest by 30th EOD.

**Comment by jonas-he** [comment]
@swathi-ssunder according to #2 we also plan on providing at least 2 additional features: **relativeTime** (time of day at the location of that sighting in "HH:MM:SS" format, already implemented in common.js) and something like a classification of the environment (not yet implemented).
I would say that we don't store theses values in the DB, but compute them when needed for an API call, because they only depend on the information we already have in the schema.

**Comment by bensLine** [comment]
ok, thanks for the update! @jonas-he will the environment feature be available at the 30th as well?

**Comment by WoH** [comment]
Hey Guys, I'm from Project E, I'll add myself and @MajorBreakfast to the conversation if you don't mind since the results will be very important for us aswell.

**Comment by jonas-he** [comment]
@bensLine probably not since im working on other things right now, but should be done by 31th.

**Comment by bensLine** [comment]
Hey @swathi-ssunder, is the API already up? :p

**Comment by swathi-ssunder** [comment]
@bensLine - The first phase of implementation is complete. However, we are facing some issues with the deployed build since yesterday. We are working on it. It should be fixed today and I will post the link to the API, with a detailed explanation of our implementation and also the data that will be available.

**Comment by sacdallago** [comment]
@bensLine if you are super impatient you can check the status of the deployment via https://hub.docker.com/r/pokemongoers/pokedata/builds/

**Comment by bensLine** [comment]
Thanks, I'm just curious ;)

**Comment by swathi-ssunder** [comment]
@bensLine - The API is [here](http://pokedata.c4e3f8c7.svc.dockerapp.io:65014/).

**Comment by bensLine** [comment]
Hey guys, thanks for the API! We have much more data now to work with :) 
@jonas-he can you name already the additional features you'll add to the poke data? so that we do not implement the same features.
you named before **relative time** and **evnironment**. If you have more details please let us know.

**Comment by MatthiasBaur** [comment]
Hello,
would you consider switching from Longitude/Latitude to Latitude/Longitude? I think it is the standard formatting.

**Comment by semioniy** [comment]
Hi, @PokemonGoers/pokedata, PredictPokemon team here.
We have a couple of questions about your API and would be grateful to get the answer.
Does your API always return about 2500 entries? If yes, can that limitation be iliminated? 2500 is not really enough.
And second, we got some data through your API, but the distribution of time there seems to be a little bit "unnormal".
![dis](https://cloud.githubusercontent.com/assets/21012972/18238507/446ba9fa-7346-11e6-93ad-c3daa6141e43.jpg)

Does the API return only the most recent gathered data? We can't really use the timestamp as a feature, if almost all the timestamps are in range of 5 minutes.
Thanx in advance.

**Comment by jonas-he** [comment]
@semioniy the only reason that there is so few data is that the server where all the listening and gathering of data takes place hasnt been set up yet (or is about to be set up, see #21).
Once we have that running we will get in the order of 50,000 sightings per 15 minutes, so we will adapt the API to deliver all sightings in a specified time range up to a certain upper bound (e.g. 1000 sightings) or implement a pagination, see #119 .

**Comment by gyachdav** [comment]
I like those numbers :)

However do not use pagination on the API this is just bad practice. Instead have a limit number of sightings by default. Then privide controls to limit

**Comment by gyachdav** [comment]
(Sorry pressed the comment button by mistake )

... Then provide controls to limit the number of sighting whether by count, area, period or payload size in Kb).

**Comment by jonas-he** [comment]
@gyachdav quoted your thoughts in the appropriate issue #119

**Comment by sacdallago** [comment]
Yep let's follow up on #119
