### ISSUE TITLE
Pokemon icons

### ISSUE THREAD

**Issue by gqinami** [PokemonGoers/PokeData#72]
Hi there PokeData group :).

We from PokeMap will need to have the pokemon icons for all pokemons, and since they will probably be used throughout all the project, we will kindly ask you for a model to be created and an endpoint that will allow us to upload the icons.

Thanks,
Team D7

**Comment by gyachdav** [comment]
Make sure we're allowed to use those. Please document all license requirements and including the attributions requirements.

**Comment by sacdallago** [comment]
@PokemonGoers/pokemap-1 has already some icons which we can use. @PokemonGoers/pokedata you can tap into that: also, save on FS should be good enough as these are some really small files.

**Comment by sacdallago** [comment]
HA! sorry @gqinami how stupid of me :D Anyway yeah, download them all https://github.com/PokemonGoers/PokeMap-1/issues/7 but I suggest you to keep a copy in your map project as well, so you don't need to go over an http request to fetch this data

**Comment by jonas-he** [comment]
@gqinami Please provide us with the icons (e.g. send me an email to jonas.heintzenberg@tum.de or upload to your favorite filehoster) and we will integrate them into the DB and create an API call to request them.

**Comment by gqinami** [comment]
Hi @jonas-he,

I sent you the email with the icons for original pokemons (151) in .gif format. All the files are named as per pokemon name. 

Thanks,
PokeMap1 group

**Comment by fabe85** [comment]
After the pokemon icons are now inserted into our develop branch with the corresponding adaptations in the remaining code (especially filler/pokemon and store/pokemon) we can close this issue now.
If some problems or further requirements are due to do we can create a follow-up issue.

**Comment by samitsv** [comment]
@gqinami please look into our api doc for getting pokemon icon by id, http://pokedata.c4e3f8c7.svc.dockerapp.io:65014/doc/#api-Pokemon-GetIconById, it gives base64encoded string which needs to be decoded when fetched

**Comment by sacdallago** [comment]
@samitsv oh wow, why don't you directly push the image back as a binary file and skip the decoding phase?

**Comment by samitsv** [comment]
@gqinami  the GetIconById api is changed: http://pokedata.c4e3f8c7.svc.dockerapp.io:65014/doc/#api-Pokemon-GetIconById, the requester gets the pokemon icon as binary data directly
http://pokedata.c4e3f8c7.svc.dockerapp.io:65014/api/pokemon/id/1/icon

**Comment by sacdallago** [comment]
They are so cute! :heart_eyes:
