### ISSUE TITLE
Docker Build failed due to warnings

### ISSUE THREAD

**Issue by swathi-ssunder** [PokemonGoers/PokeData#87]
See https://hub.docker.com/r/pokemongoers/pokedata/builds/bb2rridsa82sbazsd5k5yce/

**Comment by sacdallago** [comment]
You can avoid this by using Travis-ci (as you are using grunt anyway) which checks if the build works when you open up the PR (and not when it's merged).
If the build fails you can correct the PR previous to merging it :) it's a 30 minute change

**Comment by swathi-ssunder** [comment]
Travis-ci implemented.
Separate issues will be opened for writing tests, checking why docker logs are not being shown etc.
